server:
  port: 8081
  servlet:
    context-path: /mock-uidai

spring:
  application:
    name: mock-uidai-service
  datasource:
    url: jdbc:postgresql://localhost:5432/mock_uidai
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.mockuidai: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/mock-uidai-service.log
    max-size: 10MB
    max-history: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Mock UIDAI Service Configuration
mock-uidai:
  auth:
    token-expiration-minutes: 60
    secret-key: mockUidaiSecretKey123456789012345678901234567890
  otp:
    expiration-seconds: 300
    length: 6
  rate-limiting:
    max-requests-per-minute: 100
  verification:
    success-rate-percentage: 95